import { rimacApi } from "./api";

export interface UserResponse {
  name: string;
  lastName: string;
  birthDay: string;
}

// Generated by https://quicktype.io

export interface PlansResponse {
  list: List[];
}

export interface List {
  name: string;
  price: number;
  description: string[];
  age: number;
}

export const getInfoUser = async () => {
  const response = await rimacApi.get<UserResponse>("/user.json");
  return response.data;
};
export const getPlans = async () => {
  const response = await rimacApi.get<PlansResponse>("/plans.json");
  return response.data;
};
